# Generated by Django 4.2.10 on 2024-02-22 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='01234567890', max_length=100, null=True)),
                ('birthDate', models.DateField(default=django.utils.timezone.now, null=True)),
                ('faceBookAccount', models.URLField(default='https://example.com', null=True)),
                ('country', models.CharField(default='Country', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_picture')),
                ('activation_token', models.CharField(default='', max_length=255)),
                ('activation_token_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activation_token_expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
